### ISSUE TITLE
Error when building the repo

### ISSUE THREAD

**Issue by Doomwhite** [godot-rust/gdextension#106]
When doing cargo build I got the following error:
```
PS C:\Users\DooMWhite\Documents\Projects\Rust\gdextension> cargo build
   Compiling godot-core v0.1.0 (C:\Users\DooMWhite\Documents\Projects\Rust\gdextension\godot-core)
   Compiling godot-ffi v0.1.0 (C:\Users\DooMWhite\Documents\Projects\Rust\gdextension\godot-ffi)
error: failed to run custom build command for `godot-core v0.1.0 (C:\Users\DooMWhite\Documents\Projects\Rust\gdextension\godot-core)`

Caused by:
  process didn't exit successfully: `C:\Users\DooMWhite\Documents\Projects\Rust\gdextension\target\debug\build\godot-core-b9c74a663c3cf27c\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=C:\Users\DooMWhite\Documents\Projects\Rust\gdextension\godot-codegen/input/gen/extension_api.json
  Found GODOT4_BIN with path to executable: 'C:\Users\DooMWhite\scoop\apps\godot-beta\current\godot.exe'
  cargo:rerun-if-changed=C:\Users\DooMWhite\scoop\apps\godot-beta\current\godot.exe
  Godot version: 4.0.beta12.official.3c9bf4bc2


  --- stderr
  thread 'main' panicked at 'failed to deserialize JSON: Json Deserialize error: Key not found is_bitfield, line:1943 col:1', godot-codegen\src\api_parser.rs:229:63
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `godot-ffi v0.1.0 (C:\Users\DooMWhite\Documents\Projects\Rust\gdextension\godot-ffi)`

Caused by:
  process didn't exit successfully: `C:\Users\DooMWhite\Documents\Projects\Rust\gdextension\target\debug\build\godot-ffi-268bf447a40dcd4c\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=../godot-codegen/input/gdextension_interface.h
  cargo:rerun-if-changed=C:\ProgramData\scoop\apps\llvm\current\lib\clang\15.0.7\include\stddef.h
  cargo:rerun-if-changed=C:\ProgramData\scoop\apps\llvm\current\lib\clang\15.0.7\include/__stddef_max_align_t.h
  cargo:rerun-if-changed=C:\ProgramData\scoop\apps\llvm\current\lib\clang\15.0.7\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vcruntime.h
  cargo:rerun-if-changed=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\sal.h
  cargo:rerun-if-changed=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\concurrencysal.h
  cargo:rerun-if-changed=C:\ProgramData\scoop\apps\llvm\current\lib\clang\15.0.7\include\vadefs.h
  cargo:rerun-if-changed=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vadefs.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\stdio.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h
  cargo:rerun-if-changed=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vcruntime.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt_wstdio.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt_stdio_config.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\corecrt.h
  cargo:rerun-if-changed=C:\Users\DooMWhite\Documents\Projects\Rust\gdextension\godot-codegen/input/gen/extension_api.json
  Found GODOT4_BIN with path to executable: 'C:\Users\DooMWhite\scoop\apps\godot-beta\current\godot.exe'
  cargo:rerun-if-changed=C:\Users\DooMWhite\scoop\apps\godot-beta\current\godot.exe
  Godot version: 4.0.beta12.official.3c9bf4bc2


  --- stderr
  Build selected for Linux/Windows.
  thread 'main' panicked at 'failed to deserialize JSON: Json Deserialize error: Key not found is_bitfield, line:1943 col:1', godot-codegen\src\api_parser.rs:229:63
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
LLVM and Rust versions:

```
PS C:\Users\DooMWhite\Documents\Projects\Rust\gdextension> clang -v
clang version 15.0.7
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\ProgramData\scoop\apps\llvm\current\bin
PS C:\Users\DooMWhite\Documents\Projects\Rust\gdextension> rustc -V
rustc 1.67.0 (fc594f156 2023-01-24)
```

**Comment by Bromeon** [comment]
> Godot version: 4.0.beta12.official.3c9bf4bc2

This Godot version is far too old, can you try https://godotengine.org/article/dev-snapshot-godot-4-0-beta-17?

**Comment by Doomwhite** [comment]
With that version it worked.
