### ISSUE TITLE
Building with Docker

### ISSUE THREAD

**Issue by thebigG** [godot-rust/gdextension#32]
Hi there,

Thanks a lot for the wonderful rust port! Have been poking around with it and everything worked fine; was able to build and run it in godot4. Then I tried building inside docker and got the following error:
```
lgomez@de48fee90037:~/rsty_physics$ GODOT4_BIN=/home/lgomez/Godot_v4.0-beta6_linux.x86_64 cargo build
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.5
   Compiling quote v1.0.21
   Compiling libc v0.2.137
   Compiling glob v0.3.0
   Compiling memchr v2.5.0
   Compiling minimal-lexical v0.2.1
   Compiling regex-syntax v0.6.28
   Compiling nanoserde-derive v0.1.19
   Compiling either v1.8.0
   Compiling bindgen v0.60.1
   Compiling bitflags v1.3.2
   Compiling rustc-hash v1.1.0
   Compiling lazycell v1.3.0
   Compiling peeking_take_while v0.1.2
   Compiling shlex v1.1.0
   Compiling lazy_static v1.4.0
   Compiling paste v1.0.9
   Compiling glam v0.22.0
   Compiling once_cell v1.16.0
   Compiling clang-sys v1.4.0
   Compiling nanoserde v0.1.32
   Compiling nom v7.1.1
   Compiling venial v0.5.0
   Compiling which v4.3.0
   Compiling godot-macros v0.1.0 (https://github.com/godot-rust/gdextension?branch=master#5a8a0007)
   Compiling regex v1.7.0
   Compiling godot-codegen v0.1.0 (https://github.com/godot-rust/gdextension?branch=master#5a8a0007)
   Compiling cexpr v0.6.0
   Compiling godot-ffi v0.1.0 (https://github.com/godot-rust/gdextension?branch=master#5a8a0007)
error: failed to run custom build command for `godot-ffi v0.1.0 (https://github.com/godot-rust/gdextension?branch=master#5a8a0007)`

Caused by:
  process didn't exit successfully: `/home/lgomez/rsty_physics/target/debug/build/godot-ffi-73a26c1996e8846a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=../godot-codegen/input/gdnative_interface.h
  cargo:rerun-if-changed=/usr/lib/llvm-11/lib/clang/11.0.1/include/stddef.h
  cargo:rerun-if-changed=/usr/lib/llvm-11/lib/clang/11.0.1/include/__stddef_max_align_t.h
  cargo:rerun-if-changed=/usr/lib/llvm-11/lib/clang/11.0.1/include/stdint.h
  cargo:rerun-if-changed=/usr/include/stdint.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/libc-header-start.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/stdc-predef.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/sys/cdefs.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/long-double.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/gnu/stubs.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/gnu/stubs-64.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/timesize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/typesizes.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/time64.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wchar.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/wordsize.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/stdint-intn.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/stdio.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/libc-header-start.h
  cargo:rerun-if-changed=/usr/include/features.h
  cargo:rerun-if-changed=/usr/lib/llvm-11/lib/clang/11.0.1/include/stddef.h
  cargo:rerun-if-changed=/usr/lib/llvm-11/lib/clang/11.0.1/include/stdarg.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/FILE.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/types.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/stdio_lim.h
  cargo:rerun-if-changed=/usr/include/x86_64-linux-gnu/bits/sys_errlist.h
  cargo:rerun-if-changed=/home/lgomez/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/5a8a000/godot-codegen/input/gen/extension_api.json
  Found GODOT4_BIN with path to executable: '/home/lgomez/Godot_v4.0-beta6_linux.x86_64'
  cargo:rerun-if-changed=/home/lgomez/Godot_v4.0-beta6_linux.x86_64
  cargo:rerun-if-changed=/home/lgomez/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/5a8a000/godot-codegen/input/gen/godot_version.txt
  Godot version: 

  --- stderr
  Build selected for Linux/Windows.
  thread 'main' panicked at 'failed to parse Godot version '': Regex capture failed', /home/lgomez/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/5a8a000/godot-codegen/src/godot_exe.rs:84:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Dockerfile:
```
FROM rust:1.64
RUN apt update &&  \
    apt-get -y install clang && \
    apt-get -y install libclang-dev && \
    apt-get install -y llvm && \
    apt-get install -y sudo

RUN useradd -ms /bin/bash -G sudo lgomez
USER lgomez
WORKDIR /home/lgomez
COPY --chown=lgomez:lgomez . /home/lgomez
RUN rustup component add rustfmt
RUN rustfmt --check /home/lgomez/rsty_physics/src/*.rs
RUN cd /home/lgomez/ && wget https://downloads.tuxfamily.org/godotengine/4.0/beta6/Godot_v4.0-beta6_linux.x86_64.zip  \
    && unzip Godot_v4.0-beta6_linux.x86_64.zip
#These might be useful for wasm deployments in the future.
#RUN rustup target add wasm32-unknown-unknown
#RUN cargo install trunk
RUN cd /home/lgomez/rsty_physics && cargo clean && GODOT4_BIN=/home/lgomez/Godot_v4.0-beta6_linux.x86_64 cargo build

```
Cargo.toml:
```
[package]
name = "rsty_physics"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
godot = { git = "https://github.com/godot-rust/gdextension", branch = "master" , features = ["minimal"]}
```

I've tried comparing my host environment to the docker environment and can't seem to crack it.

Any ideas?

Thanks in advance.

Cheers,
Lorenzo

**Comment by Bromeon** [comment]
>   thread 'main' panicked at 'failed to parse Godot version '': Regex capture failed', /home/lgomez/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/5a8a000/godot-codegen/src/godot_exe.rs:84:13

It looks like the Godot executable is not run properly. If you can make `godot4 --version` work, then godot-rust should be able to pick it up (here `godot4` is a placeholder for your Godot 4 binary).

**Comment by thebigG** [comment]
Thanks a lot for the quick response!

Turns out I had a few issues :man_facepalming: . I was missing a bunch of libraries for Godot. Here is the working Dockerfile for any folks that might run into issues:

```
FROM rust:1.64
RUN apt update &&  \
    apt-get -y install clang && \
    apt-get -y install libclang-dev && \
    apt-get install -y llvm && \
    apt-get install -y sudo \
    libx11-dev \
    libxcursor-dev \
    libxinerama-dev \
    libgl1-mesa-dev \
    libglu-dev \
    libasound2-dev \
    libpulse-dev \
    libudev-dev \
    libxi-dev \
    libxrandr-dev

RUN useradd -ms /bin/bash -G sudo lgomez
USER lgomez
WORKDIR /home/lgomez
COPY --chown=lgomez:lgomez . /home/lgomez
RUN rustup component add rustfmt
RUN rustfmt --check /home/lgomez/rsty_physics/src/*.rs
RUN cd /home/lgomez/ && wget https://downloads.tuxfamily.org/godotengine/4.0/beta6/Godot_v4.0-beta6_linux.x86_64.zip  \
    && unzip Godot_v4.0-beta6_linux.x86_64.zip
#These might be useful for wasm deployments in the future.
#RUN rustup target add wasm32-unknown-unknown
#RUN cargo install trunk
env GODOT4_BIN=/home/lgomez/Godot_v4.0-beta6_linux.x86_64
RUN cd /home/lgomez/rsty_physics && cargo clean && cargo build && cargo test

```
